[project]
name = "fastemplate"
version = "0.0.0"
description = "A template for FastAPI based projects"
requires-python = ">=3.13,<3.14"
authors = [{ name = "Igor Golyanov", email = "thornograph@gmail.com" }]
readme = "README.md"
dependencies = [
    "fastapi>=0,<1",
    "loguru>=0.7,<1",
    "pydantic>=2,<3",
    "pydantic-settings>=2,<3",
    "psycopg[binary]>=3,<4",
    "sqlalchemy[asyncio]>=2.0,<3",
    "uvicorn>=0,<1",
]

[dependency-groups]
lint = [
    "mypy>=2,<3",
    "ruff>=0,<1",
]
tests = [
    "asgi-lifespan>=2,<3",
    "pytest>=9,<10",
    "pytest-asyncio>=1,<2",
    "pytest-cov>=7,<8",
    "pytest-sugar>=1,<2",
    "httpx>=0,<1",
    "testcontainers>=4,<5",
]
dev = [
    "alembic>=1.18,<2",
    "ipdb>=0,<1",
    { include-group = "lint" },
    { include-group = "tests" },
]

[tool.alembic]
script_location = "%(here)s/migrations"
prepend_sys_path = ["."]
path_separator = "os"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"

[tool.coverage.run]
omit = ["tests/*"]
concurrency = ["greenlet", "thread"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "@(abc.)?abstractmethod",
]

[tool.mypy]
python_version = "3.13"
plugins = ["pydantic.mypy"]
strict = true

enable_error_code = [
    "unreachable",
    "redundant-expr",
    "redundant-cast",
    "redundant-self",
    "possibly-undefined",
    "explicit-override",
    "mutable-override",
    "deprecated",
    "unused-awaitable",
    "ignore-without-code",
]

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [
    "ALL",
]
unfixable = [
    "ERA", # do not autoremove commented out code
]
ignore = [
    "ISC001", "COM812", # may cause conflicts when used with the formatter
    "D", # docstrings
    "FA", # from __future__ import annotations errors
    "TD", "FIX", # todos
    "G004", # f-string logging
    "TRY400", # forces logger.exception() usage over logger.error()
]

[tool.ruff.lint.per-file-ignores]
"migrations/*" = ["INP001", "ANN"]
"tests/*" = ["S1", "ANN201", "PLR2004", "PLR0913"]
