[tool.poetry]
name = "fastemplate"
version = "0.0.1"
description = "A template for FastAPI projects"
authors = ["Igor Golyanov <thornograph@gmail.com>"]
packages = [
    { include = "*", from = "src" },
]

[tool.poetry.scripts]
app = "main:main"

[tool.poetry.dependencies]
python = "~3.9"
uvicorn = "^0.14.0"
fastapi = "^0.66.0"
requests = "^2.23.0"
sqlalchemy = { "extras" = ["mypy"], version = "^1.4.20" }
asyncpg = "^0.23.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-xdist = { extras = ["psutil"], version = "^2.2.1" }
pylint = "^2.8.3"
isort = "^5.8.0"
docformatter = "^1.4"
black = "^21.6b0"
mypy = "^0.910"
ipython = "^7.25.0"

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
follow_imports = "silent"
show_column_numbers = true

[[tool.mypy.overrides]]
module = ["uvicorn"]
ignore_missing_imports = true

[tool.pylint.master]
fail-under = 7.5

[tool.pylint.messages_control]
disable = [
    # functions should mainly be short and self-explanatory
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    # pydantic models usually have none
    "too-few-public-methods",
    "logging-fstring-interpolation"
]
# ignore pydantic no-name-in-module error
extension-pkg-allow-list = ["pydantic"]

[tool.pylint.miscellaneous]
# only treat FIXMEs as worthy warnings
notes = ["FIXME"]

[tool.pylint.format]
max-line-length = 120

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
