[tool.poetry]
name = "fastemplate"
version = "0.0.1"
description = "A template for FastAPI projects"
authors = ["Igor Golyanov <thornograph@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.9"
uvicorn = "^0.13.4"
fastapi = "^0.63.0"
ipython = "^7.22.0"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
isort = "^5.6.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
