"""Initial.

Revision ID: f9debf2d4638
Revises:
Create Date: 2021-07-18 23:33:33.988949
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f9debf2d4638"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "example",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_example_id"), "example", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_example_id"), table_name="example")
    op.drop_table("example")
    # ### end Alembic commands ###
