name: CI

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Prepare environment
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
      - name: Lint
        run: |
          make lint

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Prepare environment
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
      - name: Tests
        run: |
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./tmp
          use_oidc: true

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Build
      run: |
        export APP_VERSION=$(git describe --tags 2>/dev/null || echo "dev")
        export SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
        docker build --build-arg APP_VERSION=$APP_VERSION -t fastemplate:$GITHUB_ACTOR-$SHORT_COMMIT_SHA .
