name: CI

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: 1.2.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Prepare environment
        run: |
            pip install poetry==$POETRY_VERSION
            poetry config virtualenvs.create false
            poetry install --verbose
      - name: Pylint
        run: |
          make pylint
      - name: Mypy
        run: |
          make mypy

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    services:
      test_db:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: test_db
          POSTGRES_PASSWORD: test_db
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    env:
      POETRY_VERSION: 1.2.0
      DB_DSN: "postgresql+asyncpg://test_db:test_db@localhost:5432/test_db"
      MIGRATION_DSN: "postgresql+psycopg2://test_db:test_db@localhost:5432/test_db"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Prepare environment
        run: |
          pip install poetry==$POETRY_VERSION
          poetry config virtualenvs.create false
          poetry install --verbose
      - name: Tests
        run: |
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./tmp


  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        export SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
        docker build -t fastemplate:$GITHUB_ACTOR-$SHORT_COMMIT_SHA .
